---
name: Funciones y Tipos de Datos, revisado
locale: es
type: learning
beta: false
teacher_info: "* Funciones y Tipos de Datos, revisado\n  \n¡Hola! Quizás no te diste
  cuenta, pero ya tenés las bases de la programación: ya sabés declarar funciones
  y procedimientos, usar variables, tomar decisiones \n\n  - no hay un tablero, pero
  igual podemos hacer muchas cosas!\n\n   * Functions, declaración\n    > \n   * Functions,
  uso\n   * Tipos de datos, introduccion\n   * Booleanos\n   * ¡Más cuentas!\n   *
  Tirando los dados\n   * ¿Y que tal si...?"
language: javascript
id_format: '%05d'
order:
- 1
- 2
- 16
- 4
- 5
- 8
- 9
- 6
- 13
- 14
- 15
- 11
- 12
- 7
- 3
